Automation/Areas/AdminPanel/Controllers/UserManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Automation.Areas.AdminPanel.Controllers
{
    [Area("AdminPanel")]
    public class UserManagerController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Automation/Areas/UserPanel/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Automation.Areas.UserPanel.Controllers
{
    [Area("UserPanel")]
    public class UserController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Automation/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Automation.Controllers
{
    public class AccountController : Controller
    {
        public IActionResult Login()
        {
            return View();
        }
    }
}

Automation/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Automation.DataModelLayer.Models;

namespace Automation.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Automation/Areas/AdminPanel/Views/Shared/_AdminPanelLayout.cshtml
<!DOCTYPE html>
<html lang="fa" dir="rtl">

<head>
    <!-- START - MetaTags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Content-Language" content="fa">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>پنل کاربری - سیستم اتوماسیون اداری تحت وب </title>
    <!-- END - MetaTags -->
    <!-- START - stylesheets -->
    <link href="~/Panel/assets/css/icons/icomoon/styles.css" rel="stylesheet" type="text/css">
    <link href="~/Panel/assets/css/bootstrap.css" rel="stylesheet" type="text/css">
    <link href="~/Panel/assets/css/core.css" rel="stylesheet" type="text/css">
    <link href="~/Panel/assets/css/components.css" rel="stylesheet" type="text/css">
    <link href="~/css/customStyle.css" rel="stylesheet" />
    <!--Top Loading-->


</head>

<body class="navbar-top">
    <!-- START - Main Navibar -->
    <partial name="_navbarPartial"/>
    <!-- END - Main Navibar -->
    <!-- START - Main Content -->
    <div class="page-container">

        <!-- START - Page Content -->
        <div class="page-content">

            <!-- START - Main Sidebar -->
            <partial name="_sidebarPartial" />
            <!-- END - Main Sidebar -->
            <!-- START - Main Content -->
            <div class="content-wrapper">

                <!-- START - View header -->
                <partial name="_headerPartial"/>
                <!-- END - View header -->
                <!-- Content area -->
                <div class="content">

                    <!-- START - View Content -->
                    <div class="row">
                        @RenderBody()
                    </div>
                    <!-- END - View Content -->


                </div>
                <!-- /content area -->
                <!-- Footer -->

                <partial name="_footerPartial"/>

                <!-- /footer -->
            </div>
            <!-- END - Main Content -->

        </div>
        <!-- END - Page Content -->

    </div>
    <!-- END - Main Content -->
    <script type="text/javascript" src="~/Panel/assets/js/plugins/loaders/pace.min.js"></script>
    <script type="text/javascript" src="~/Panel/assets/js/core/libraries/jquery.min.js"></script>
    <script type="text/javascript" src="~/Panel/assets/js/core/libraries/bootstrap.min.js"></script>
    <script type="text/javascript" src="~/Panel/assets/js/plugins/ui/nicescroll.min.js"></script>
    <script type="text/javascript" src="~/Panel/assets/js/core/app.js"></script>
    @RenderSection("Scripts", required: false)

    <!-- END - theme JS files -->
</body>

</html>

Automation/Areas/AdminPanel/Views/Shared/_navbarPartial.cshtml
<div class="navbar navbar-fixed-top" style="background-color:#9b9d9d;">
    <div class="navbar-header">
        <a class="navbar-brand" href="#"></a>

        <ul class="nav navbar-nav visible-xs-block">
            <li><a data-toggle="collapse" data-target="#navbar-mobile" style="color:white;"><i class="icon-tree5"></i></a></li>
            <li><a class="sidebar-mobile-main-toggle" style="color:black;"><i class="icon-paragraph-justify3"></i></a></li>
        </ul>

    </div>

    <div class="navbar-collapse collapse" id="navbar-mobile" style="background-color:#9b9d9d;">
        <ul class="nav navbar-nav">
            <li>
                <a class="sidebar-control sidebar-main-toggle hidden-xs" style="color:black;"><i class="icon-paragraph-justify3"></i></a>
            </li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
            <li class="dropdown dropdown-user">
                <a class="dropdown-toggle" data-toggle="dropdown" style="color:black;">

                    <span>امکانات شخصی</span>
                    <i class="caret"></i>
                </a>

                <ul class="dropdown-menu dropdown-menu-right">
                    <li><a href="#"><i class="icon-user-plus"></i>پروفایل من</a></li>
                    <li>
                        <a href="#">
                            <span class="badge badge-info pull-right">3</span> <i class="icon-comment-discussion"></i>آخرین پیام ها
                        </a>
                    </li>
                    <li class="divider"></li>
                    <li><a href="#"><i class="icon-switch2"></i> خروج از سیستم</a></li>
                </ul>
            </li>
        </ul>
    </div>
</div>

Automation/Areas/AdminPanel/Views/Shared/_sidebarPartial.cshtml
<div class="sidebar sidebar-main" style="background-color:#d4d1d1;">
    <div class="sidebar-content">

        <!-- START - User menu -->
        <div class="sidebar-user">
            <div class="category-content">
                <div class="media">
                    <a href="#" class="media-left">
                    </a>
                    <div class="media-body">
                        <span class="media-heading text-semibold">سعید بحرانی فرد</span>
                        <div class="text-size-mini text-muted">
                            <i class="icon-pin text-size-small"></i> &nbsp; پنل ادمین
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- END - User menu -->
        <!-- START - Main navigation -->
        <div class="sidebar-category sidebar-category-visible">
            <div class="category-content no-padding">

                <!-- START - Item Navigation -->
                <ul class="navigation navigation-main" style="color:black;">

                    <!-- START - Item Navigation Header -->
                    <li class="navigation-header">
                        <span> داشبورد اختصاصی کاربران</span> <i class="icon-menu"
                                                                 title="صفحه اصلی"></i>
                    </li>
                    <li class="active">
                        <a href="index.html">
                            <i class="icon-home4"></i>
                            <span>پیشخوان</span>
                        </a>
                    </li>
                    <li>
                    </li>

                    <li>
                        <a href="#"><i class="icon-users"></i><span>مدیریت کاربران</span></a>
                    </li>
                    <li>
                        <a href="#"><i class="icon-office"></i><span>مشاغل</span></a>
                    </li>
                    <li>
                        <a href="#"><i class="icon-traffic-cone"></i><span>کنترل ورود و خروج</span></a>
                    </li>
                    <li>
                        <a href="#"><i class="icon-office"></i><span>انتساب شغل</span></a>
                    </li>
                    <li>
                        <a href="#"><i class="icon-forward3"></i><span>ارسال پیام به کاربران</span></a>
                    </li>

                    <li>
                        <a href="#"><i class="icon-reminder"></i><span>ثبت یادآوری</span></a>
                    </li>
                    <li>
                        <a href="#"><i class="icon-sync"></i><span>اجزای سیستم</span></a>
                    </li>
                    <li>
                        <a href="#"><i class="icon-accessibility"></i><span>کنترل دسترسی ها</span></a>
                    </li>
                </ul>
                <!-- END - Item Navigation -->

            </div>
        </div>
        <!-- END - Main navigation -->

    </div>
</div>

Automation/Areas/AdminPanel/Views/UserManager/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<div class="content">
    <div class="panel panel-heading" style="box-shadow:1px 1px 0 0 gray; ">
        <span style="font-weight:bold">
            <i class="glyphicon glyphicon-user" ></i>
            لیست کاربران سامانه
        </span>
    </div>

    <div style="margin-bottom:5px">
        <a class="btn cusomGreen1" asp-controller="UserManager" asp-action="AddUser">
            <i class="glyphicon glyphicon-plus"></i>
            افزودن کاربر جدید
        </a>
    </div>
    <div >
        <div class="table-responsive">
            <table class="table table-bordered table-striped table-hover" style="border-radius:2px; box-shadow:3px 3px 1px gray;">
                <thead>
                    <tr>
                        <td>ردیف</td>
                        <td>نام</td>
                        <td>نام خانوادگی</td>
                        <td>شماره تماس</td>
                        <td>کد پرسنلی</td>
                        <td>تام کاربری</td>
                        <td>تصویر</td>
                        <td>امضا</td>
                        <td>وضعیت</td>
                        <td>عملیات</td>
                    </tr>
                </thead>
                <tbody>

                </tbody>
            </table>
        </div>
    </div>
</div>

Automation/Areas/UserPanel/Views/Shared/_UserPanelLayout.cshtml
<!DOCTYPE html>
<html lang="fa" dir="rtl">

<head>
    <!-- START - MetaTags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Content-Language" content="fa">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>پنل کاربری - سیستم اتوماسیون اداری تحت وب</title>
    <!-- END - MetaTags -->
    <!-- START - stylesheets -->
    <link href="~/Panel/assets/css/icons/icomoon/styles.css" rel="stylesheet" type="text/css">
    <link href="~/Panel/assets/css/bootstrap.css" rel="stylesheet" type="text/css">
    <link href="~/Panel/assets/css/core.css" rel="stylesheet" type="text/css">
    <link href="~/Panel/assets/css/components.css" rel="stylesheet" type="text/css">



</head>
<body class="navbar-top">
    <!-- START - Main Navibar -->
    <partial name="_navbarPartial"/>
    <!-- END - Main Navibar -->
    <!-- START - Main Content -->
    <div class="page-container">

        <!-- START - Page Content -->
        <div class="page-content">

            <!-- START - Main Sidebar -->
            <partial name="_sidebarPartial"/>
            <!-- END - Main Sidebar -->
            <!-- START - Main Content -->
            <div class="content-wrapper">

                <!-- START - View header -->
                <partial name="_headerPartial"/>
                <!-- END - View header -->
                <!-- Content area -->
                <div class="content">

                    <!-- START - View Content -->
                    <div class="row">
                        @RenderBody()
                    </div>
                    <!-- END - View Content -->


                </div>
                <!-- /content area -->
                <!-- Footer -->

               <partial name="_footerPartial"/>

                <!-- /footer -->
            </div>
            <!-- END - Main Content -->

        </div>
        <!-- END - Page Content -->

    </div>
    <!-- END - Main Content -->
    <!--Top Loading-->
    <script type="text/javascript" src="~/Panel/assets/js/plugins/loaders/pace.min.js"></script>
    <script type="text/javascript" src="~/Panel/assets/js/core/libraries/jquery.min.js"></script>
    <script type="text/javascript" src="~/Panel/assets/js/core/libraries/bootstrap.min.js"></script>
    <script type="text/javascript" src="~/Panel/assets/js/plugins/ui/nicescroll.min.js"></script>
    <script type="text/javascript" src="~/Panel/assets/js/core/app.js"></script>
    @RenderSection("Scripts", required: false)
    <!-- END - theme JS files -->
</body>

</html>

Automation/Areas/UserPanel/Views/Shared/_footerPartial.cshtml
<div class="breadcrumb-line" style="background-color:#e0dbdb; border-top:1px solid gray; text-align:center; bottom:1px !important; position:fixed; width:100%;">
    <div class="col-md-offset-2 col-md-6">
        <span style="color: black;"> سیستم اتوماسیون اداری تحت وب - کلیه حقوق مادی و معنوی این نرم افزار محفوظ می باشد </span>
    </div>
</div>

Automation/Areas/UserPanel/Views/Shared/_headerPartial.cshtml
<div class="page-header">
    <div class="page-header-content">
        <div style="padding-top:10px;">
            <!--<h4>
                <i class="icon-arrow-right6 position-left"></i> <span class="text-semibold">خانه</span>
                - داشبورد
            </h4>-->
        </div>
    </div>

    <div class="breadcrumb-line">
        <ul class="breadcrumb">
            <li><a href="index.html"><i class="icon-home2 position-left"></i> صفحه اصلی</a></li>
            <li class="active">پیشخوان</li>
        </ul>

        <ul class="breadcrumb-elements">
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <i class="icon-gear position-left"></i>
                    تاریخچه ورود به سیستم
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu dropdown-menu-right">
                    <li><a href="#"><i class="icon-eye8"></i> ورود امروز: 7:31 صبح</a></li>
                    <li><a href="#"><i class="icon-eye8"></i> ورود دیروز: 7:39 صبح</a></li>
                    <li><a href="#"><i class="icon-eye8"></i> خروج دیروز: 16:35 عصر</a></li>
                    <li class="divider"></li>
                    <li><a href="#"><i class="icon-calendar3"></i>تاریخچه ورود به سیستم</a></li>
                </ul>
            </li>
        </ul>
        <!-- <ul class="breadcrumb-elements">
            <li class="dropdown">
                <a lass="dropdown-toggle">
                    <div class="text-size-small badgeDate bg-abiyeKhooboo-600">امروز :
                        سه شنبه 12، تیر، 1398</div>
                </a>
            </li>
            <li class="dropdown">
                <a lass="dropdown-toggle">
                    <span class="heading-text badgeTime bg-abiyeKhooboo-600"> آخرین ورود به پنل مدیریت :
                        07:35 صبح </span>
                </a>
            </li>
        </ul> -->
    </div>
</div>

Automation/Areas/UserPanel/Views/Shared/_navbarPartial.cshtml
<div class="navbar navbar-fixed-top" style="background-color:#d9dbdc;">
    <div class="navbar-header">
        <a class="navbar-brand" href="#"></a>

        <ul class="nav navbar-nav visible-xs-block">
            <li><a data-toggle="collapse" data-target="#navbar-mobile" style="color:black;"><i class="icon-tree5"></i></a></li>
            <li><a class="sidebar-mobile-main-toggle" style="color:black;"><i class="icon-paragraph-justify3"></i></a></li>
        </ul>

    </div>

    <div class="navbar-collapse collapse" id="navbar-mobile" style="background-color:#d9dbdc;">
        <ul class="nav navbar-nav">
            <li>
                <a class="sidebar-control sidebar-main-toggle hidden-xs" style="color:black;"><i class="icon-paragraph-justify3"></i></a>
            </li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
            <li class="dropdown dropdown-user">
                <a class="dropdown-toggle" data-toggle="dropdown" style="color:black;">

                    <span>امکانات شخصی</span>
                    <i class="caret"></i>
                </a>

                <ul class="dropdown-menu dropdown-menu-right">
                    <li><a href="#"><i class="icon-user-plus"></i>پروفایل من</a></li>
                    <li>
                        <a href="#">
                            <span class="badge badge-info pull-right">3</span> <i class="icon-comment-discussion"></i>آخرین پیام ها
                        </a>
                    </li>
                    <li class="divider"></li>
                    <li><a href="#"><i class="icon-switch2"></i> خروج از سیستم</a></li>
                </ul>
            </li>
        </ul>
    </div>
</div>

Automation/Areas/UserPanel/Views/Shared/_sidebarPartial.cshtml
<div class="sidebar sidebar-main" style="background-color:#d4d1d1;">
    <div class="sidebar-content">

        <!-- START - User menu -->
        <div class="sidebar-user">
            <div class="category-content">
                <div class="media">
                    <a href="#" class="media-left">
                    </a>
                    <div class="media-body">
                        <span class="media-heading text-semibold">سعید بحرانی فرد</span>
                        <div class="text-size-mini text-muted">
                            <i class="icon-pin text-size-small"></i> &nbsp;پنل کاربران ( مسئول مالی )
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- END - User menu -->
        <!-- START - Main navigation -->
        <div class="sidebar-category sidebar-category-visible">
            <div class="category-content no-padding">

                <!-- START - Item Navigation -->
                <ul class="navigation navigation-main" style="color:black;">

                    <!-- START - Item Navigation Header -->
                    <li class="navigation-header">
                        <span> داشبورد اختصاصی کاربران</span> <i class="icon-menu"
                                                                 title="صفحه اصلی"></i>
                    </li>
                    <li class="active">
                        <a href="index.html">
                            <i class="icon-home4"></i>
                            <span>پیشخوان</span>
                        </a>
                    </li>
                    <li>
                    </li>
                    <!-- END - Item Navigation Header -->
                    <!-- START - مطالب و محتوا -->
                    <li>
                        <a href="#"><i class="icon-bookmark"></i><span>کارتابل</span></a>

                        <ul>
                            <li>
                                <a href="#"><i class="icon-book2"></i> <span>همه نامه های وارده</span></a>

                            </li>
                            <li>
                                <a href="#"><i class="icon-book"></i> <span>نامه های خوانده شده</span></a>

                            </li>
                            <li>
                                <a href="#"><i class="icon-envelop"></i> <span>نامه های خوانده نشده</span></a>
                            </li>
                            <li>
                                <a href="#"><i class="icon-forrst"></i> <span>نامه های اقدام فوری</span></a>
                            </li>
                            <li>
                                <a href="#"><i class="icon-forrst2"></i> <span>نامه های محرمانه</span></a>
                            </li>
                            <li>
                                <a href="#"><i class="icon-notebook"></i> <span>یادداشت های رسیده</span></a>
                            </li>
                            <li>
                                <a href="#"><i class="icon-book3"></i> <span>نامه های ارجاع داده شده</span></a>
                            </li>

                            <li>
                                <a href="#"><i class="icon-reminder"></i> <span>نمایش یادآوری ها</span></a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#"><i class="icon-forward"></i><span>بازیافت</span></a>

                        <ul>
                            <li>
                                <a href="#"><i class="icon-forward2"></i><span>نامه های ارسالی</span></a>
                            </li>

                            <li>
                                <a href="#"><i class="icon-grab"></i><span>پیگیری</span></a>
                            </li>

                            <li>
                                <a href="#"><i class="icon-notebook"></i><span>یادداشت های ارسالی</span></a>
                            </li>
                            <li>
                                <a href="#"><i class="icon-repo-forked"></i><span>نامه های ارجاع داده شده</span></a>
                            </li>
                        </ul>
                    </li>

                    <!-- END - مطالب و محتوا -->
                    <!-- START - اسناد، پرونده ها و پروژه ها -->
                    <li>
                        <a href="#"><i class="icon-forward"></i><span>عملیات</span></a>

                        <ul>
                            <li>
                                <a href="#"><i class="icon-printer"></i><span>ایجاد نامه</span></a>
                            </li>

                            <li>
                                <a href="#"><i class="icon-notebook"></i><span>ایجاد یادداشت</span></a>
                            </li>

                            <li>
                                <a href="#"><i class="icon-reminder"></i><span>ثبت یادآوری</span></a>
                            </li>
                            <li>
                                <a href="#"><i class="icon-bubble7"></i><span>پیش نویس</span></a>
                            </li>
                            <li>
                                <a href="#"><i class="icon-codepen"></i><span>ثبت اسناد خارجه</span></a>
                            </li>
                        </ul>
                    </li>

                    <!-- END - اسناد، پرونده ها و پروژه ها -->
                    <!-- START - مدیریت مالی -->
                    <li>
                        <a href="#"><i class="icon-paperplane"></i><span>خبرنامه</span></a>

                        <ul>
                            <li>
                                <a href="#"><i class="icon-new"></i><span>اخبار و اطلاعیه ها</span></a>
                            </li>
                        </ul>
                    </li>
                    <!-- END - مدیریت مالی -->
                    <!-- START - مدیریت کاربران -->
                    <li>
                        <a href="#"><i class="icon-forward"></i><span>ارزشیابی پرسنل</span></a>

                        <ul>
                            <li>
                                <a href="#"><i class="icon-point-up"></i><span>ثبت کارکرد روزانه</span></a>
                            </li>

                            <li>
                                <a href="#"><i class="icon-chart"></i><span>نمایش کارکرد پرسنل</span></a>
                            </li>
                        </ul>
                    </li>
                    <!-- END - مدیریت کاربران -->
                    <!-- START - پیکربندی سیستم -->
                    <li>
                        <a href="#"><i class="icon-shrink5"></i><span>تنظیمات</span></a>

                        <ul>
                            <li>
                                <a href="#"><i class="icon-key"></i><span>تغییر رمز عبور</span></a>
                            </li>

                            <li>
                                <a href="#"><i class="icon-user"></i><span>پروفایل</span></a>
                            </li>
                        </ul>
                    </li>
                    <!-- END - پیکربندی سیستم -->

                </ul>
                <!-- END - Item Navigation -->

            </div>
        </div>
        <!-- END - Main navigation -->

    </div>
</div>

Automation/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Automation/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Automation/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}



<div class="row">
<p>hi</p>
</div>

Automation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Automation</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <!--add font awsome-->
    <link href="~/css/fonts/font-awesome/css/font-awesome.min.css" rel="stylesheet" />

</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Automation</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer class="mt-8 py-4 text-center text-gray-500 text-sm border-t ">
            این پنل متعلق به  <a href="https://sunflower-dev.com" class="text-blue-500 font-bold " style="text-decoration:none">آزاده شریفی سلطانی </a> می باشد
        </footer>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        @await RenderSectionAsync("Scripts", required: false)
        <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>